### ISSUE TITLE
What does the client verifying the server name in the challenge == configured server name prevent?

### ISSUE THREAD

**Issue by davidxia** [spotify/crtauth#26]
Hi @nresare,

The client checks the server name in the challenge equals the server name the client itself was given (here https://github.com/spotify/crtauth/blob/6a624579ae8fae827adcf47be6b61273f82dcf81/crtauth/client.py#L57). @gimaker, @rohansingh, and I were wondering what kind of attack this would prevent.

If client-to-server communication is over TLS, the attacker can't inject a challenge in the middle of the handshake unless they had the TLS private key in which case there would probably be bigger problems.

The attacker can simply set its crtauth server name to match that of the legit crtauth server. And if it managed to get the client to send back a signed challenge , the attacker would only have some bytes signed by the client. This response doesn't seem like it can be used for much as the attacker shouldn't know the crtauth secret the legit server is using. So any signed challenge couldn't be used to get a real auth token.

We have multiple crtauth servers and the client might want to round-robin requests to all of them. So the server names will change. We're thinking of setting all the clients and servers to just have a fixed crtauth server name like `foo.com` just to work around this check. Maybe we're missing something?

**Comment by nresare** [comment]
How nice to have a discussion of the actual protocol. The thing that makes it hard for an attacker to modify the server name field to anything she wants is the HMAC code at the end of the challenge.

The thinking here is that we want to protect against the situation where an attacker can place herself in the middle of the connection and intercept and modify payload. Without the server_name field the attacker could then conceivably trick the user into signing a challenge for the wrong server and re-direct the response to obtain a token from a more sensitive service.

My thinking with regards to round robin and many servers is since the client will compare challenge hostname and the host that it attempted to connect anyway, that hostname needs to be the symbolic CNAME hostname (service.DOMAIN) anyway and not the actual hostname site-service-N.site.DOMAIN. As long as all round robin authentication servers share the same HMAC secret they should be able to verify each others's challenges and tokens.

**Comment by nresare** [comment]
One could argue that HTTPS protects against a MITM problem, but given the amount of attacks that has been seen in recent years against HTTPS on various levels, protection in depth seems like a good strategy.

**Comment by davidxia** [comment]
@nresare Ah thanks. After thinking about it more it makes sense to us. Just to double check we understand:

You're saying the server name in the challenge prevents an attacker who's MITMed one client-server crtauth handshake with server A to get auth tokens from another crt server B that might protect more sensitive resources.  This is because the client signs the entire challenge which includes the server name A. An attacker who changes the server name A will get a different signature that will be rejected by the crt server B.

**Comment by nresare** [comment]
That would be one case, yes. The A and B would need to use the same key for the attack to work though, but misconfigured servers is definitely a thing.

Another case is when the attacker detects that you are attempting to authenticate to server A and initiates the same authentication procedure towards server B and feeds you the challenge from B. If the client can't check the hostname of the challenge she may very well sign a challenge that gives the attacker access to B.

If a successful MITM is mounted, your token is still compromised so you are in trouble anyway, but this setup makes it avoids the scenario when you are successfully authenticating against the wrong server.

**Comment by davidxia** [comment]
Cool thanks!
